function [h] = sig_plot(I,O,ymax,titlestring)
    %This function takes as an input the area array generated by
    %LoadEdgeData and plots area(µm) vs time (seconds). There is also a
    %commented section that will draw a line on the plot, which is useful
    %if you are plotting data from a live perturbation
    
    
    meansig = nanmean(O.SigInt_areanorm,2); %finds the mean at each time point
    time = (0:1:O.frame_num-1);
    timelabel = (0:I.timestep:I.timestep*(O.frame_num-1));
    
    
    shadedErrorBar(timelabel,meansig,nanstd(O.SigInt_areanorm,0,2));
    
    if isnan(I.injection) == 0
        hold on
        if I.injection > 1
            inject = I.injection - 1
        else
            inject = I.injection
        end
        xline = I.timestep*(inject);
        h = plot([xline xline],[0 1000])
    end
    
    xlabel('Time (seconds)')
    ylabel('Area-Normalized Signal Intensity (microns)')
    axis([0 max(timelabel) 0 ymax])
    
    if nargin == 4
        title(titlestring)
    end

end